[package]
name = "monitor_blank"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.5.1"
env_logger = "0.11.8"
libc = "0.2.180"
log = "0.4.29"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.12"
